version: "3.8"

services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=carteiradeinvestimentos
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    healthcheck:
      test: ["CMD-SHELL", "psql -U root -d carteiradeinvestimentos -c 'SELECT 1;'"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  postgres-network:
    driver: bridge